apiVersion: v1
kind: Pod
metadata:
  name: helm-upgrade-whizard-monitoring-test
  namespace: kubesphere-monitoring-system
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: ks-controller-manager
          namespaces:
          - kubesphere-system
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 36000000 && cp -r /tmp/helm-executor-source/. /tmp/helm-executor && helm upgrade --history-max
      2 --insecure-skip-tls-verify --kubeconfig kube.config --kube-as-user system:serviceaccount:kubesphere-monitoring-system:helm-executor.whizard-monitoring
      whizard-monitoring whizard-monitoring.tgz --namespace kubesphere-monitoring-system
      --values values.yaml --set tags.extension=true,tags.agent=false,global.portal.url=http://ks-console.kubesphere-system.svc:30880,whizardAgentProxy.enabled=false,dcgmExporter.enabled=false,cadvisor.enabled=false
      --post-renderer /tmp/helm-executor/helm-post-render.sh --debug --wait --wait-for-jobs
      --timeout 10m0s
    env:
    - name: HELM_CACHE_HOME
      value: /tmp/helm-executor
    image: registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.27.12
    imagePullPolicy: IfNotPresent
    name: helm
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - mountPath: /tmp/helm-executor-source
      name: source
    - mountPath: /tmp/helm-executor
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cqc2w
      readOnly: true
    workingDir: /tmp/helm-executor
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: HELM_CACHE_HOME
      value: /tmp/helm-executor
    - name: HOOK_ACTION
      value: upgrade
    - name: CLUSTER_ROLE
      value: host
    - name: CLUSTER_NAME
      value: "host"
    - name: INSTALL_TAG
      value: "extension"
    - name: INSTALLPLAN_NAME
      value: whizard-monitoring
    image: frezes/wiztelemetry-upgrade:v0.1.0
    imagePullPolicy: IfNotPresent
    name: helm-init
    volumeMounts:
    - mountPath: /tmp/helm-executor
      name: source
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cqc2w
      readOnly: true
    workingDir: /tmp/helm-executor
  volumes:
  - configMap:
      defaultMode: 493
      name: helm-upgrade-whizard-monitoring-smw7qn       # Update according to the current environment
    name: source
  - emptyDir: {}
    name: data
  - name: kube-api-access-cqc2w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace